# Generated by Django 5.2 on 2025-04-14 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammaticalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Grammatical Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrammaticalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('grammatical_meaning', models.TextField()),
                ('usage', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='grammar_app.grammaticalcategory')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzbek_text', models.TextField()),
                ('english_translation', models.TextField(blank=True)),
                ('grammatical_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='grammar_app.grammaticalform')),
            ],
        ),
    ]
