# Generated by Django 5.2 on 2025-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammaticalform',
            name='usage',
            field=models.CharField(blank=True, choices=[("bog'lovchi", "Bog'lovchi"), ('yuklama', 'Yuklama'), ("ko'makchi", "Ko'makchi")], max_length=100),
        ),
    ]
