# Generated by Django 5.2 on 2025-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0002_alter_grammaticalform_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammaticalform',
            name='usage',
            field=models.CharField(choices=[("Ko'makchi", "Ko'makchi"), ("Bog'lovchi", "Bog'lovchi"), ('Yuklama', 'Yuklama')], max_length=100, verbose_name='Turkumi'),
        ),
    ]
