# Generated by Django 5.2 on 2025-04-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0004_grammaticalform_special_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_colloquial',
            field=models.CharField(blank=True, max_length=100, verbose_name="So'zlashuv"),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_journalistic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Publitsistik'),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_literary',
            field=models.CharField(blank=True, max_length=100, verbose_name='Badiiy'),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_official',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rasmiy'),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_scientific',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ilmiy'),
        ),
    ]
