# Generated by Django 5.2 on 2025-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0005_alter_grammaticalform_style_colloquial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_colloquial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_journalistic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_literary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_official',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grammaticalform',
            name='style_scientific',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
