# Generated by Django 5.2 on 2025-04-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0006_alter_grammaticalform_style_colloquial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UslubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yordamchi_soz', models.CharField(max_length=255, verbose_name="Yordamchi so'z")),
                ('maxsus_kodi', models.CharField(blank=True, max_length=100, verbose_name='Maxsus kodi')),
                ('grammatik_manosi', models.TextField(blank=True, verbose_name="Grammatik ma'nosi")),
                ('badiiy', models.CharField(blank=True, max_length=100, verbose_name='Badiiy')),
                ('ilmiy', models.CharField(blank=True, max_length=100, verbose_name='Ilmiy')),
                ('publitsistik', models.CharField(blank=True, max_length=100, verbose_name='Publitsistik')),
                ('rasmiy', models.CharField(blank=True, max_length=100, verbose_name='Rasmiy')),
                ('sozlashuv', models.CharField(blank=True, max_length=100, verbose_name="So'zlashuv")),
            ],
            options={
                'verbose_name': "Uslub ma'lumoti",
                'verbose_name_plural': "Uslub ma'lumotlari",
            },
        ),
    ]
