# Generated by Django 5.2 on 2025-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0007_uslubdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslubdata',
            name='badiiy',
            field=models.BooleanField(default=False, verbose_name='Badiiy'),
        ),
        migrations.AlterField(
            model_name='uslubdata',
            name='ilmiy',
            field=models.BooleanField(default=False, verbose_name='Ilmiy'),
        ),
        migrations.AlterField(
            model_name='uslubdata',
            name='maxsus_kodi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maxsus kodi'),
        ),
        migrations.AlterField(
            model_name='uslubdata',
            name='publitsistik',
            field=models.BooleanField(default=False, verbose_name='Publitsistik'),
        ),
        migrations.AlterField(
            model_name='uslubdata',
            name='rasmiy',
            field=models.BooleanField(default=False, verbose_name='Rasmiy'),
        ),
        migrations.AlterField(
            model_name='uslubdata',
            name='sozlashuv',
            field=models.BooleanField(default=False, verbose_name="So'zlashuv"),
        ),
    ]
