# Generated by Django 5.2 on 2025-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0012_wordsynonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=255, verbose_name="So'zning maxsus kodi")),
                ('auxiliary_word', models.CharField(max_length=255, verbose_name="Yordamchi so'z")),
                ('grammatical_code', models.CharField(max_length=255, verbose_name='Grammatik kodi')),
                ('primary_meaning', models.TextField(verbose_name="So'zning birlamchi grammatik ma'nosi")),
                ('secondary_meaning', models.TextField(blank=True, verbose_name='Ikkilamchi')),
                ('third_meaning', models.TextField(blank=True, verbose_name='Uchinchi')),
                ('fourth_meaning', models.TextField(blank=True, verbose_name="To'rtinchi")),
                ('fifth_meaning', models.TextField(blank=True, verbose_name='Beshinchi')),
                ('sixth_meaning', models.TextField(blank=True, verbose_name='Oltinchi')),
                ('seventh_meaning', models.TextField(blank=True, verbose_name='Yettinchi')),
                ('eighth_meaning', models.TextField(blank=True, verbose_name='Sakkizinchi')),
                ('ninth_meaning', models.TextField(blank=True, verbose_name="To'qqizinchi")),
                ('tenth_meaning', models.TextField(blank=True, verbose_name="O'ninchi")),
            ],
            options={
                'verbose_name': "Kodlangan so'z",
                'verbose_name_plural': "Kodlangan so'zlar",
                'ordering': ['special_code'],
            },
        ),
    ]
