# Generated by Django 5.2 on 2025-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0013_codedword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedword',
            name='auxiliary_word',
            field=models.CharField(db_column='yordamchi_soz', max_length=255, verbose_name="Yordamchi so'z"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='eighth_meaning',
            field=models.TextField(blank=True, db_column='sakkizinchi_grammatik_manosi', null=True, verbose_name="Sakkizinchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='fifth_meaning',
            field=models.TextField(blank=True, db_column='beshinchi_grammatik_manosi', null=True, verbose_name="Beshinchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='fourth_meaning',
            field=models.TextField(blank=True, db_column='tortinchi_grammatik_manosi', null=True, verbose_name="To'rtinchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='grammatical_code',
            field=models.CharField(db_column='grammatik_kodi', max_length=255, verbose_name='Grammatik kodi'),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='ninth_meaning',
            field=models.TextField(blank=True, db_column='toqqizinchi_grammatik_manosi', null=True, verbose_name="To'qqizinchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='primary_meaning',
            field=models.TextField(db_column='sozning_birlamchi_grammatik_manosi', verbose_name="So'zning birlamchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='secondary_meaning',
            field=models.TextField(blank=True, db_column='ikkilamchi_grammatik_manosi', null=True, verbose_name="Ikkilamchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='seventh_meaning',
            field=models.TextField(blank=True, db_column='yettinchi_grammatik_manosi', null=True, verbose_name="Yettinchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='sixth_meaning',
            field=models.TextField(blank=True, db_column='oltinchi_grammatik_manosi', null=True, verbose_name="Oltinchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='special_code',
            field=models.CharField(db_column='sozning_maxsus_kodi', max_length=255, verbose_name="So'zning maxsus kodi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='tenth_meaning',
            field=models.TextField(blank=True, db_column='oninchi_grammatik_manosi', null=True, verbose_name="O'ninchi grammatik ma'nosi"),
        ),
        migrations.AlterField(
            model_name='codedword',
            name='third_meaning',
            field=models.TextField(blank=True, db_column='uchinchi_grammatik_manosi', null=True, verbose_name="Uchinchi grammatik ma'nosi"),
        ),
    ]
