# Generated by Django 5.2 on 2025-04-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0014_alter_codedword_auxiliary_word_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodedWord',
        ),
    ]
