# Generated by Django 5.2 on 2025-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0015_delete_codedword'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammatikManoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yordamchi_soz', models.CharField(max_length=255, verbose_name="Yordamchi so'z")),
                ('grammatik_manosi', models.TextField(verbose_name="So'zning grammatik ma'nosi")),
                ('badiiy_uslub', models.TextField(blank=True, verbose_name='Badiiy uslub')),
                ('ilmiy_uslub', models.TextField(blank=True, verbose_name='Ilmiy uslub')),
                ('publitsistik_uslub', models.TextField(blank=True, verbose_name='Publitsistik uslub')),
                ('rasmiy_uslub', models.TextField(blank=True, verbose_name='Rasmiy uslub')),
                ('sozlashuv_uslubi', models.TextField(blank=True, verbose_name="So'zlashuv uslubi")),
            ],
            options={
                'verbose_name': "Grammatik ma'no bo'yicha ma'lumot",
                'verbose_name_plural': "Grammatik ma'no bo'yicha ma'lumotlar",
                'ordering': ['yordamchi_soz'],
            },
        ),
    ]
