# Generated by Django 5.2 on 2025-04-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0016_grammatikmanodata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammatikmanodata',
            options={'ordering': ['grammatik_manosi'], 'verbose_name': "Grammatik ma'no bo'yicha ma'lumot", 'verbose_name_plural': "Grammatik ma'no bo'yicha ma'lumotlar"},
        ),
        migrations.RemoveField(
            model_name='grammatikmanodata',
            name='yordamchi_soz',
        ),
    ]
