# Generated by Django 5.2 on 2025-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0017_alter_grammatikmanodata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammaticalMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliary_word', models.CharField(max_length=255, verbose_name="Yordamchi so'z")),
                ('grammatical_meaning', models.TextField(verbose_name="Grammatik ma'no")),
            ],
            options={
                'verbose_name': 'Grammatical Meaning',
                'verbose_name_plural': 'Grammatical Meanings',
                'ordering': ['auxiliary_word'],
            },
        ),
    ]
