# Generated by Django 5.2 on 2025-04-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0018_grammaticalmeaning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrammaticalMeaning',
        ),
    ]
