# Generated by Django 5.2 on 2025-04-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0019_delete_grammaticalmeaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='DavriylikiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yordamchi_soz', models.CharField(max_length=255, verbose_name="Yordamchi so'z")),
                ('grammatik_manosi', models.TextField(blank=True, verbose_name="Grammatik ma'nosi")),
                ('period_11_12', models.CharField(blank=True, max_length=255, verbose_name='XI-XII asr')),
                ('period_13_14', models.CharField(blank=True, max_length=255, verbose_name='XIII-XIV asr')),
                ('period_15_18', models.CharField(blank=True, max_length=255, verbose_name='XV-XVIII asr')),
                ('period_19', models.CharField(blank=True, max_length=255, verbose_name='XIX asr')),
                ('period_20', models.CharField(blank=True, max_length=255, verbose_name='XX asr')),
            ],
            options={
                'verbose_name': "So'z davriyligi",
                'verbose_name_plural': "So'z davriyligiga ko'ra",
            },
        ),
    ]
