# Generated by Django 5.2 on 2025-04-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0020_davriylikidata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davriylikidata',
            name='grammatik_manosi',
        ),
        migrations.RemoveField(
            model_name='davriylikidata',
            name='yordamchi_soz',
        ),
    ]
