# Generated by Django 5.2 on 2025-04-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0021_remove_davriylikidata_grammatik_manosi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinonimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammatik_manosi', models.TextField(verbose_name="So'zning grammatik ma'nosi")),
                ('sinonimlar', models.TextField(verbose_name='Sinonimlar')),
                ('misol', models.TextField(blank=True, verbose_name='Misol')),
                ('english', models.TextField(blank=True, verbose_name='In English')),
            ],
            options={
                'verbose_name': 'Sinonim',
                'verbose_name_plural': 'Sinonimlar',
                'ordering': ['grammatik_manosi'],
            },
        ),
    ]
